name: dat158
dependencies:
- python >= 3.7.0
- pip
- pytest
- flask
- ipython
- ipykernel
- ipywidgets
- jupyter
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- git
- numpy
- matplotlib
- pandas
- scikit-learn >= 0.20
- scipy
- seaborn
- conda-forge::category_encoders
- hyperopt
- pip:
  - pip >= 19.0
  - kaggle
  - pandas-profiling
  - xlrd
  - eli5
  - pdpbox
  - nbdime
  
